module.exports.deals = [
	{
		company: 'pierce industrial tire',
		priority: 11,
		hot: false,
		hd: true,
		contact: 'jay lynn',
		stage: 'negotiation',
		status: 'open',
		lastActivityDays: 24,
		lastActivityDate: '03/13/2023',
		value: 18646,
		name: 'tcx635',
		type: 'meeting',
		daysOpen: 1346,
		createDate: '07/30/2019',
		zone: 'waycross',
		segment: 'tire dealer',
		source: 'hunter - jay mullineaux',
		distributor: 'smith garage',
		competition: '',
		reason: '',
		closed: '03/13/2023',
		lostReason: '',
	},
];
